# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
orbs:
  node: circleci/node@5.1.0
  gh-pages: sugarshin/gh-pages@1.0.1
jobs:
  test:
    docker:
      - image: 'cimg/node:14.20.1'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run cov:send
      - run: npm run cov:check
  publish-docs:
    executor: gh-pages/default
    steps:
      - checkout
      - run: npm run doc:html
      - run: npm run doc:publish
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: 66:28:0f:96:81:5c:9e:4c:2a:fe:39:76:d7:20:19:cd

workflows:
  build:
    jobs:
      - test
      - publish-docs:
          filters:
            branches:
              only:
                - main
          requires:
            - test
